name: Run build and test

on:
  push:
    branches-ignore:
      - 'next'
      - 'www'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          version: 'latest'

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: 6.0

      - name: Setup mongodb-tools
        run: |
          wget https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2204-x86_64-100.6.1.deb
          sudo apt install ./mongodb-database-tools-*-100.6.1.deb
          mongorestore --version          

      - name: Install dependencies
        run: npm install

      - name: Big Build
        run: npm run build

      - name: Run tests
        run: gulp all